config/routes.rb
Rails.application.routes.draw do
  resources :ailments, only: [:new, :create, :destroy]
  resources :prescriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :patients, only: [:show]
  resources :appointments
  resources :specialties, only: [:index, :show] do
    resources :doctors, only: [:new, :create, :edit, :update, :show, :destroy]
  end
  get '/doctors_index', to: 'doctors#index', as: 'doctors'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'session'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/doctor_signup', to: 'doctor_signup#new', as: 'doctor_signup'
  post '/doctor_signup', to: 'doctor_signup#create'
  get '/doctor_edit', to: 'doctor_signup#edit', as: 'doctor_edit'
  patch '/doctor_edit', to: 'doctor_signup#update'
  get '/patient_signup', to: 'patient_signup#new', as: 'patient_signup'
  post '/patient_signup', to: 'patient_signup#create'
  get '/patient_edit', to: 'patient_signup#edit', as: 'patient_edit'
  patch '/patient_edit', to: 'patient_signup#update'
  post '/resolve_ailment', to: 'ailments#resolve_ailment'
  post '/unresolve_ailment', to: 'ailments#unresolve_ailment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ailment.rb
# frozen_string_literal: true

class Ailment < ApplicationRecord
  belongs_to :patient
  has_many :appointments, dependent: :destroy
  validates :description, presence: true
  validates :first_noticed_on, presence: true

  def self.unresolved_for_current_user(current_user)
    all.select do |ailment|
      ailment.patient == current_user.role && ailment.resolved_status == false
    end
  end

  def time_since_first_noticed
    result = (Date.today - first_noticed_on).to_i
    if result <= 31
      "#{result} days"
    elsif result > 31 && result <= 90
      w_result = result / 7
      "#{w_result} weeks"
    elsif result > 90 && result <= 540
      m_result = result / 30
      "#{m_result} months"
    else
      y_result = result / 365
      "#{y_result} years"
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def sort_alphabetically(persons)
    persons.uniq.sort_by do |person|
      person.last_name.downcase
    end
  end

  def sort_appointments_by_time
    appointments.sort_by(&:scheduled_for)
  end
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  belongs_to :ailment
  validates :duration_in_minutes, presence: true
  validates :duration_in_minutes, numericality: true
  validates :scheduled_for, presence: true

  has_many :prescriptions

  def self.for_current_user(current_user)
    all.select do |appointment|
      appointment.doctor == current_user.role
    end
  end

  def date_and_patient
    "#{scheduled_for.strftime('%A, %b. %-d, %Y @ %l:%M %P')}\
    (#{patient.full_name})"
  end
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord
  belongs_to :specialty, optional: true
  has_many :appointments
  has_many :patients, through: :appointments
  has_one :users, as: :role
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :location_city, presence: true
  validates :years_in_practice, presence: true
  validates :years_in_practice, numericality: true

  def self.for_specialty(specialty)
    all.select do |doctor|
      doctor.specialty_id == specialty.id
    end
  end

  def doctor_with_specialty_and_location
    "Dr. #{full_name} (#{specialty.name}) - #{location_city}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  has_many :ailments
  has_many :appointments
  has_many :doctors, through: :appointments
  has_one :users, as: :role
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def sort_ailments_by_created_at
    ailments.sort_by(&:created_at)
  end
end

app/models/prescription.rb
# frozen_string_literal: true

class Prescription < ApplicationRecord
  belongs_to :appointment
  validates :drug, presence: true
  validates :dosage_in_milligrams, presence: true
  validates :dosage_in_milligrams, numericality: true
  delegate :doctor, to: :appointment

  def self.for_appointments(appointment_collection)
    prescriptions = all.select do |prescription|
      appointment_collection.include?(prescription.appointment)
    end
    prescriptions.sort_by do |prescription|
      prescription.appointment.scheduled_for
    end
  end
end

app/models/specialty.rb
# frozen_string_literal: true

class Specialty < ApplicationRecord
  has_many :doctors
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  belongs_to :role, polymorphic: true
  accepts_nested_attributes_for :role
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :password_confirmation, length: { minimum: 6 }
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find_by(id: params[:id])
    @patients = @doctor.sort_alphabetically(@doctor.patients)
    @appointments = @doctor.sort_appointments_by_time
    @prescriptions = Prescription.for_appointments(@appointments)
    @prescription = Prescription.new
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  def show
    @patient = Patient.find_by(id: params[:id])
    @doctors = @patient.sort_alphabetically(@patient.doctors)
    @ailments = @patient.sort_ailments_by_created_at
    @appointments = @patient.sort_appointments_by_time
    @prescriptions = Prescription.for_appointments(@appointments)
    unless current_user.role == @patient || @doctors.include?(current_user.role)
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
end

app/helpers/ailments_helper.rb
# frozen_string_literal: true

module AilmentsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
end

app/helpers/doctor_signup_helper.rb
# frozen_string_literal: true

module DoctorSignupHelper
end

app/helpers/doctors_helper.rb
# frozen_string_literal: true

module DoctorsHelper
end

app/helpers/patient_signup_helper.rb
# frozen_string_literal: true

module PatientSignupHelper
end

app/helpers/patients_helper.rb
# frozen_string_literal: true

module PatientsHelper
end

app/helpers/prescriptions_helper.rb
# frozen_string_literal: true

module PrescriptionsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/specialties_helper.rb
# frozen_string_literal: true

module SpecialtiesHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/patients/show.html.erb
<h2><%= @patient.full_name %></h2>
<% if current_user.role == @patient %>
  <%= link_to "Report New Ailment", new_ailment_path %>
  <br>
  <% unless @ailments.empty? %>
    <%= link_to "Schedule New Appointment", new_appointment_path %>
    <br>
  <% end %>
<% end %>
<br>
<h3>
  <% if current_user.role == @patient %>
    My
  <% end %>
  Upcoming Appointments:
</h3>
<% @appointments.each do |appointment| %>
  <ul>
    <li>
      <small><i>Physician:</i></small> <%= link_to "Dr. #{appointment.doctor.full_name}", specialty_doctor_path(appointment.doctor.specialty, appointment.doctor) %>
    </li>
    <li>
      <small><i>Date/Time:</i></small> <%= link_to appointment.scheduled_for.strftime("%A, %b. %-d, %Y @ %l:%M %P"), appointment_path(appointment) %>
    </li>
    <li>
      <small><i>Duration:</i></small> <%= appointment.duration_in_minutes %> min.
    </li>
    <li>
      <small><i>Reason:</i></small> <%= appointment.ailment.description %>
    </li>
    <% if current_user.role == @patient || current_user.role == appointment.doctor %>
      <%= form_tag appointment_path(appointment), method: 'delete' do %>
        <%= hidden_field_tag "id", appointment.id %>
        <%= submit_tag "Cancel Appointment" %>
      <% end %>
    <% end %>
  </ul>
<% end %>
<% if @ailments.empty? %>
  <small><i>You have not reported any ailments. Click <%= link_to "here", new_ailment_path %> to report a new ailment before scheduling an appointment.</i></small>
  <br>
  <br>
<% elsif @appointments.empty? %>
  <small><i>You have no scheduled appointments. Click <%= link_to "here", new_appointment_path %> to schedule a new appointment.</i></small>
  <br>
  <br>
<% end %>
<br>

<h3>
  <% if current_user.role == @patient %>
    My
  <% end %>
  Medical History:
</h3>
<% @ailments.each do |ailment| %>
  <ul>
    <li>
      <small><i>Ailment:</i></small> <%= ailment.description %>
    </li>
    <% if ailment.resolved_status == false %>
      <li>
        <small><i>Status:</i></small> This ailment has persisted for <%= ailment.time_since_first_noticed %>.
      </li>
      <% if current_user.role == @patient %>
        <%= form_tag '/resolve_ailment', method: 'post' do %>
          <%= hidden_field_tag "id", ailment.id %>
          <%= submit_tag "Mark Resolved" %>
        <% end %>
      <% end %>
    <% else %>
      <li>
        <small><i>Status:</i></small> Resolved <small><i>- We're glad you're feeling better!</i></small>
      </li>
      <% if current_user.role == @patient %>
        <%= form_tag '/unresolve_ailment', method: 'post' do %>
          <%= hidden_field_tag "id", ailment.id %>
          <%= submit_tag "Mark Unresolved" %>
        <% end %>
      <% end %>
    <% end %>
    <% if current_user.role == @patient %>
      <%= form_tag ailment_path(ailment), method: 'delete' do %>
        <%= hidden_field_tag "id", ailment.id %>
        <%= submit_tag "Remove" %>
      <% end %>
    <% end %>
  </ul>
<% end %>
<% if @ailments.empty? %>
  <small><i>You have not reported any ailments. Click <%= link_to "here", new_ailment_path %> to report a new ailment.</i></small>
  <br>
  <br>
<% end %>
<br>

<h3>
  <% if current_user.role == @patient %>
    My
  <% end %>
  Doctors:
</h3>
<% if @ailments.empty? %>
  <small><i>You have not reported any ailments. Click <%= link_to "here", new_ailment_path %> to report a new ailment before scheduling an appointment.</i></small>
  <br>
  <br>
<% elsif @appointments.empty? %>
  <small><i>You have no scheduled appointments. Click <%= link_to "here", new_appointment_path %> to schedule a new appointment.</i></small>
  <br>
  <br>
<% end %>
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to "Dr. #{doctor.full_name}", specialty_doctor_path(doctor.specialty, doctor) %>
    </li>
  <% end %>
</ul>
<br>

<h3>
  <% if current_user.role == @patient %>
    My
  <% end %>
  Prescriptions:
</h3>
<% if @ailments.empty? %>
  <small><i>You have not reported any ailments. Click <%= link_to "here", new_ailment_path %> to report a new ailment before scheduling an appointment.</i></small>
  <br>
  <br>
<% elsif @appointments.empty? %>
  <small><i>You have no scheduled appointments. Click <%= link_to "here", new_appointment_path %> to schedule a new appointment.</i></small>
  <br>
  <br>
<% elsif @prescriptions.empty? %>
  <small><i>You have no prescriptions. Click <%= link_to "here", new_appointment_path %> to schedule an appointment.</i></small>
  <br>
  <br>
<% end %>
<% @prescriptions.each do |prescription| %>
  <ul>
    <li>
      <small><i>Drug:</i></small> <%= prescription.drug %>
    </li>
    <li>
      <small><i>Dosage:</i></small> <%= prescription.dosage_in_milligrams %> mg
    </li>
    <li>
      <small><i>Reason:</i></small> <%= prescription.appointment.ailment.description %>
    </li>
    <li>
      <small><i>Physician:</i></small> <%= link_to "Dr. #{prescription.appointment.doctor.last_name}", specialty_doctor_path(prescription.appointment.doctor.specialty, prescription.appointment.doctor) %>
    </li>
    <li>
      <small><i>Appointment Date:</i></small> <%= link_to prescription.appointment.scheduled_for.strftime("%b. %-d, %Y"), appointment_path(prescription.appointment) %>
      <% if current_user.role == prescription.appointment.doctor %>
        <small>(<%= link_to "edit", edit_prescription_path(prescription) %>)</small>
        </li>
        <%= form_tag prescription_path(prescription), method: 'delete' do %>
          <%= hidden_field_tag "id", prescription.id %>
          <%= submit_tag "Cancel Prescription" %>
        <% end %>
      <% else %>
        </li>
      <% end %>
  </ul>
<% end %>
<br>
<br>
<%= link_to "All Medical Specialties", specialties_path %>
<br>
<%= link_to "All Registered Physicians", doctors_path %>