config/routes.rb
Rails.application.routes.draw do
  resources :ailments, only: [:new, :create, :destroy]
  resources :prescriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :patients, only: [:show]
  resources :appointments
  resources :specialties, only: [:index, :show] do
    resources :doctors, only: [:new, :create, :edit, :update, :show, :destroy]
  end
  get '/doctors_index', to: 'doctors#index', as: 'doctors'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'session'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/doctor_signup', to: 'doctor_signup#new', as: 'doctor_signup'
  post '/doctor_signup', to: 'doctor_signup#create'
  get '/doctor_edit', to: 'doctor_signup#edit', as: 'doctor_edit'
  patch '/doctor_edit', to: 'doctor_signup#update'
  get '/patient_signup', to: 'patient_signup#new', as: 'patient_signup'
  post '/patient_signup', to: 'patient_signup#create'
  get '/patient_edit', to: 'patient_signup#edit', as: 'patient_edit'
  patch '/patient_edit', to: 'patient_signup#update'
  post '/resolve_ailment', to: 'ailments#resolve_ailment'
  post '/unresolve_ailment', to: 'ailments#unresolve_ailment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ailment.rb
# frozen_string_literal: true

class Ailment < ApplicationRecord
  belongs_to :patient
  has_many :appointments, dependent: :destroy
  validates :description, presence: true
  validates :first_noticed_on, presence: true

  def self.unresolved_for_current_user(current_user)
    all.select do |ailment|
      ailment.patient == current_user.role && ailment.resolved_status == false
    end
  end

  def time_since_first_noticed
    result = (Date.today - first_noticed_on).to_i
    if result <= 31
      "#{result} days"
    elsif result > 31 && result <= 90
      w_result = result / 7
      "#{w_result} weeks"
    elsif result > 90 && result <= 540
      m_result = result / 30
      "#{m_result} months"
    else
      y_result = result / 365
      "#{y_result} years"
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def sort_alphabetically(persons)
    persons.uniq.sort_by do |person|
      person.last_name.downcase
    end
  end

  def sort_appointments_by_time
    appointments.sort_by(&:scheduled_for)
  end
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  belongs_to :ailment
  validates :duration_in_minutes, presence: true
  validates :duration_in_minutes, numericality: true
  validates :scheduled_for, presence: true

  has_many :prescriptions

  def self.for_current_user(current_user)
    all.select do |appointment|
      appointment.doctor == current_user.role
    end
  end

  def date_and_patient
    "#{scheduled_for.strftime('%A, %b. %-d, %Y @ %l:%M %P')}\
    (#{patient.full_name})"
  end
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord
  belongs_to :specialty, optional: true
  has_many :appointments
  has_many :patients, through: :appointments
  has_one :users, as: :role
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :location_city, presence: true
  validates :years_in_practice, presence: true
  validates :years_in_practice, numericality: true

  def self.for_specialty(specialty)
    all.select do |doctor|
      doctor.specialty_id == specialty.id
    end
  end

  def doctor_with_specialty_and_location
    "Dr. #{full_name} (#{specialty.name}) - #{location_city}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  has_many :ailments
  has_many :appointments
  has_many :doctors, through: :appointments
  has_one :users, as: :role
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def sort_ailments_by_created_at
    ailments.sort_by(&:created_at)
  end
end

app/models/prescription.rb
# frozen_string_literal: true

class Prescription < ApplicationRecord
  belongs_to :appointment
  validates :drug, presence: true
  validates :dosage_in_milligrams, presence: true
  validates :dosage_in_milligrams, numericality: true
  delegate :doctor, to: :appointment

  def self.for_appointments(appointment_collection)
    prescriptions = all.select do |prescription|
      appointment_collection.include?(prescription.appointment)
    end
    prescriptions.sort_by do |prescription|
      prescription.appointment.scheduled_for
    end
  end
end

app/models/specialty.rb
# frozen_string_literal: true

class Specialty < ApplicationRecord
  has_many :doctors
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  belongs_to :role, polymorphic: true
  accepts_nested_attributes_for :role
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :password_confirmation, length: { minimum: 6 }
end

app/controllers/doctor_signup_controller.rb
# frozen_string_literal: true

class DoctorSignupController < ApplicationController
  def new
    @user = User.new(role: Doctor.new)
  end

  def create
    @user = User.new(user_params)
    @user.role = Doctor.new(
      specialty_id: params[:user][:role_attributes][:specialty_id],
      location_city: params[:user][:role_attributes][:location_city],
      years_in_practice: params[:user][:role_attributes][:years_in_practice],
      first_name: params[:user][:role_attributes][:first_name],
      last_name: params[:user][:role_attributes][:last_name]
    )
    if @user.role.save && @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    @user = User.find_by(id: current_user.id)
    if @user.update(user_params) && @user.role.update(
      specialty_id: params[:user][:role_attributes][:specialty_id],
      location_city: params[:user][:role_attributes][:location_city],
      years_in_practice: params[:user][:role_attributes][:years_in_practice],
      first_name: params[:user][:role_attributes][:first_name],
      last_name: params[:user][:role_attributes][:last_name]
    )
      redirect_to specialty_doctor_path(current_user.role.specialty,
                                        current_user.role)
    else
      render :edit
    end
  end

  # private
  #
  # def doctor_params
  #   params.require(:user).permit(role_attributes: [
  #       :specialty_id,
  #       :location_city,
  #       :years_in_practice,
  #       :first_name,
  #       :last_name
  #     ]
  #   )
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
end

app/helpers/ailments_helper.rb
# frozen_string_literal: true

module AilmentsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
end

app/helpers/doctor_signup_helper.rb
# frozen_string_literal: true

module DoctorSignupHelper
end

app/helpers/doctors_helper.rb
# frozen_string_literal: true

module DoctorsHelper
end

app/helpers/patient_signup_helper.rb
# frozen_string_literal: true

module PatientSignupHelper
end

app/helpers/patients_helper.rb
# frozen_string_literal: true

module PatientsHelper
end

app/helpers/prescriptions_helper.rb
# frozen_string_literal: true

module PrescriptionsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/specialties_helper.rb
# frozen_string_literal: true

module SpecialtiesHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/doctor_signup/edit.html.erb
<h2>Edit Personal Information</h2>
<%= form_for(@user , url: doctor_edit_path) do |f| %>
  <% if @user.role.errors.any? %>
    <h3>Doctor Fields Errors:</h3>
    <ul class="errors">
      <% @user.role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <br>
  <% end %>
  <% if @user.errors.any? %>
    <h3>User Fields Errors:</h3>
    <ul class="errors">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <br>
  <% end %>
  <%= f.fields_for(:role, @user.role) do |ff| %>
    <%= ff.label "Specialty:" %>
    <%= ff.collection_select(:specialty_id, Specialty.all, :id, :name) %>
    <br>
    <br>
    Location City, State: <%= ff.text_field :location_city %>
    <br>
    <br>
    How many years have you been in practice? <%= ff.number_field :years_in_practice %>
    <br>
    <br>
    First Name: <%= ff.text_field :first_name %>
    <br>
    <br>
    Last Name: <%= ff.text_field :last_name %>
  <% end %>
  <br>
  <br>
  <%= f.label "E-Mail:" %>
  <%= f.text_field(:email, id: "email") %>
  <br>
  <br>
  <%= f.label "Password:" %>
  <%= f.password_field(:password, id: "password") %>
  <br>
  <br>
  Confirm Password: <%= f.password_field(:password_confirmation, id: "password_confirmation") %>
  <br>
  <br>
  <br>
  <%= f.submit "Update My Information"%>
<% end %>

app/views/doctor_signup/new.html.erb
<h2>New Doctor Sign-Up</h2>
<%= form_for(@user , url: doctor_signup_path) do |f| %>
  <% if @user.role.errors.any? %>
    <h3>Doctor Fields Errors:</h3>
    <ul class="errors">
      <% @user.role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <br>
  <% end %>
  <% if @user.errors.any? %>
    <h3>User Fields Errors:</h3>
    <ul class="errors">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <br>
  <% end %>
  <%= f.fields_for(:role, Doctor.new) do |ff| %>
    <%= ff.label "Specialty:" %>
    <%= ff.collection_select(:specialty_id, Specialty.all, :id, :name) %>
    <br>
    <br>
    Location City, State: <%= ff.text_field :location_city %>
    <br>
    <br>
    How many years have you been in practice? <%= ff.number_field :years_in_practice %>
    <br>
    <br>
    First Name: <%= ff.text_field :first_name %>
    <br>
    <br>
    Last Name: <%= ff.text_field :last_name %>
  <% end %>
  <br>
  <br>
  <%= f.label "E-Mail:" %>
  <%= f.text_field(:email, id: "email") %>
  <br>
  <br>
  <%= f.label "Password:" %>
  <%= f.password_field(:password, id: "password") %>
  <br>
  <br>
  Confirm Password: <%= f.password_field(:password_confirmation, id: "password_confirmation") %>
  <br>
  <br>
  <br>
  <%= f.submit "Sign Up"%>
<% end %>