config/routes.rb
Rails.application.routes.draw do
  resources :ailments, only: [:new, :create, :destroy]
  resources :prescriptions, only: [:new, :create, :edit, :update, :destroy]
  resources :patients, only: [:show]
  resources :appointments
  resources :specialties, only: [:index, :show] do
    resources :doctors, only: [:new, :create, :edit, :update, :show, :destroy]
  end
  get '/doctors_index', to: 'doctors#index', as: 'doctors'
  root 'static_pages#home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create', as: 'session'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/doctor_signup', to: 'doctor_signup#new', as: 'doctor_signup'
  post '/doctor_signup', to: 'doctor_signup#create'
  get '/doctor_edit', to: 'doctor_signup#edit', as: 'doctor_edit'
  patch '/doctor_edit', to: 'doctor_signup#update'
  get '/patient_signup', to: 'patient_signup#new', as: 'patient_signup'
  post '/patient_signup', to: 'patient_signup#create'
  get '/patient_edit', to: 'patient_signup#edit', as: 'patient_edit'
  patch '/patient_edit', to: 'patient_signup#update'
  post '/resolve_ailment', to: 'ailments#resolve_ailment'
  post '/unresolve_ailment', to: 'ailments#unresolve_ailment'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ailment.rb
# frozen_string_literal: true

class Ailment < ApplicationRecord
  belongs_to :patient
  has_many :appointments, dependent: :destroy
  validates :description, presence: true
  validates :first_noticed_on, presence: true

  def self.unresolved_for_current_user(current_user)
    all.select do |ailment|
      ailment.patient == current_user.role && ailment.resolved_status == false
    end
  end

  def time_since_first_noticed
    result = (Date.today - first_noticed_on).to_i
    if result <= 31
      "#{result} days"
    elsif result > 31 && result <= 90
      w_result = result / 7
      "#{w_result} weeks"
    elsif result > 90 && result <= 540
      m_result = result / 30
      "#{m_result} months"
    else
      y_result = result / 365
      "#{y_result} years"
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def sort_alphabetically(persons)
    persons.uniq.sort_by do |person|
      person.last_name.downcase
    end
  end

  def sort_appointments_by_time
    appointments.sort_by(&:scheduled_for)
  end
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  belongs_to :ailment
  validates :duration_in_minutes, presence: true
  validates :duration_in_minutes, numericality: true
  validates :scheduled_for, presence: true

  has_many :prescriptions

  def self.for_current_user(current_user)
    all.select do |appointment|
      appointment.doctor == current_user.role
    end
  end

  def date_and_patient
    "#{scheduled_for.strftime('%A, %b. %-d, %Y @ %l:%M %P')}\
    (#{patient.full_name})"
  end
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord
  belongs_to :specialty, optional: true
  has_many :appointments
  has_many :patients, through: :appointments
  has_one :users, as: :role
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :location_city, presence: true
  validates :years_in_practice, presence: true
  validates :years_in_practice, numericality: true

  def self.for_specialty(specialty)
    all.select do |doctor|
      doctor.specialty_id == specialty.id
    end
  end

  def doctor_with_specialty_and_location
    "Dr. #{full_name} (#{specialty.name}) - #{location_city}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  has_many :ailments
  has_many :appointments
  has_many :doctors, through: :appointments
  has_one :users, as: :role
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def sort_ailments_by_created_at
    ailments.sort_by(&:created_at)
  end
end

app/models/prescription.rb
# frozen_string_literal: true

class Prescription < ApplicationRecord
  belongs_to :appointment
  validates :drug, presence: true
  validates :dosage_in_milligrams, presence: true
  validates :dosage_in_milligrams, numericality: true
  delegate :doctor, to: :appointment

  def self.for_appointments(appointment_collection)
    prescriptions = all.select do |prescription|
      appointment_collection.include?(prescription.appointment)
    end
    prescriptions.sort_by do |prescription|
      prescription.appointment.scheduled_for
    end
  end
end

app/models/specialty.rb
# frozen_string_literal: true

class Specialty < ApplicationRecord
  has_many :doctors
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  belongs_to :role, polymorphic: true
  accepts_nested_attributes_for :role
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :password_confirmation, length: { minimum: 6 }
end

app/controllers/ailments_controller.rb
# frozen_string_literal: true

class AilmentsController < ApplicationController
  def new
    if current_user.role_type == "Patient"
      @ailment = Ailment.new
    else
      redirect_to root_path
    end
  end

  def create
    @ailment = Ailment.new(ailment_params)
    if @ailment.save
      redirect_to patient_path(@ailment.patient)
    else
      render :new
    end
  end

  def destroy
    ailment = Ailment.find_by(id: params[:id])
    ailment.destroy
    redirect_to patient_path(ailment.patient)
  end

  def resolve_ailment
    ailment = Ailment.find_by(id: params[:id])
    ailment.resolved_status = true
    ailment.save
    redirect_to patient_path(ailment.patient)
  end

  def unresolve_ailment
    ailment = Ailment.find_by(id: params[:id])
    ailment.resolved_status = false
    ailment.save
    redirect_to patient_path(ailment.patient)
  end

private

  def ailment_params
    params.require(:ailment).permit(
      :first_noticed_on,
      :description
    )
          .merge(
            patient_id: current_user.role.id
          )
  end
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find_by(id: params[:id])
    @patients = @doctor.sort_alphabetically(@doctor.patients)
    @appointments = @doctor.sort_appointments_by_time
    @prescriptions = Prescription.for_appointments(@appointments)
    @prescription = Prescription.new
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
end

app/helpers/ailments_helper.rb
# frozen_string_literal: true

module AilmentsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/appointments_helper.rb
# frozen_string_literal: true

module AppointmentsHelper
end

app/helpers/doctor_signup_helper.rb
# frozen_string_literal: true

module DoctorSignupHelper
end

app/helpers/doctors_helper.rb
# frozen_string_literal: true

module DoctorsHelper
end

app/helpers/patient_signup_helper.rb
# frozen_string_literal: true

module PatientSignupHelper
end

app/helpers/patients_helper.rb
# frozen_string_literal: true

module PatientsHelper
end

app/helpers/prescriptions_helper.rb
# frozen_string_literal: true

module PrescriptionsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/specialties_helper.rb
# frozen_string_literal: true

module SpecialtiesHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/ailments/new.html.erb
<h2>Report New Ailment</h2>
<%= form_for @ailment do |f| %>
  <% if @ailment.errors.any? %>
    <h3>Errors:</h3>
    <ul class="errors">
      <% @ailment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <br>
  <% end %>
  <%= f.label "When did you first notice the issue?" %>
  <br>
  <%= f.date_field(:first_noticed_on, id: "first_noticed_on", max: Date.today) %>
  <br>
  <br>
  Brief Description:
  <br>
  <%= f.text_area(:description, id: "description") %>
  <br>
  <br>
  <br>
  <%= f.submit "Report Ailment" %>
<% end %>

app/views/doctors/index.html.erb
<u><h2>All Registered Physicians</h2></u>
<% @doctors.each do |doctor| %>
  <p>
    <b><%= link_to "Dr. #{doctor.full_name}", specialty_doctor_path(doctor.specialty, doctor) %></b>
    <br>
- <i><%= link_to doctor.specialty.name, specialty_path(doctor.specialty) %></i>
  </p>
<% end %>

app/views/doctors/show.html.erb
<h2><%= @doctor.full_name %>, M.D.</h2>
- <i><%= link_to @doctor.specialty.name, specialty_path(@doctor.specialty) %></i>
<% if current_user.role == @doctor %>
  <br>
  <br>
  <h3>
    My Public Profile:
  </h3>
<% end %>
<ul>
  <li>
    <% if current_user.role == @doctor %>
      You have
    <% else %>
      Dr. <%= @doctor.last_name %> has
    <% end %>
    been in practice for <%= @doctor.years_in_practice %> years
  </li>
  <li>
    Located in <%= @doctor.location_city %>
  </li>
  <li>
    Connected with <%= @patients.count %> patients through <i>Benjamin's Medical Directory</i>
  </li>
</ul>
<% if current_user.role_type == "Patient" %>
  <br>
  <%= link_to "Schedule New Appointment", new_appointment_path %>
  <br>
  <br>
<% end %>
<br>
<% if current_user.role == @doctor %>
  <h3>
    My Upcoming Appointments:
  </h3>
  <% if @appointments.empty? %>
    <small><i>You have no scheduled appointments.</i></small>
    <br>
    <br>
  <% end %>
  <div id="appointments">
    <button id="show-appointments">Show Appointments</button>
  </div>
  <br>
  <h3>
    My Patients:
  </h3>
  <% if @patients.empty? %>
    <small><i>You have no patients.</i></small>
    <br>
    <br>
  <% end %>
  <ul>
    <% @patients.each do |patient| %>
      <li>
        <%= link_to patient.full_name, patient_path(patient) %>
      </li>
    <% end %>
  </ul>
  <br>
  <h3>
    My Prescriptions:
  </h3>
  <% if @prescriptions.empty? && @appointments.empty? %>
    <small><i>You have no prescriptions.</i></small>
    <br>
    <br>
  <% elsif @prescriptions.empty? && !@appointments.empty? %>
    <small><i>You have no prescriptions. Create a new prescription.</i></small>
    <br>
    <%= render 'prescriptions/form' %>
    <br>
  <% else %>
    <i>Create New Prescription</i>
    <br>
    <br>
    <%= render 'prescriptions/form' %>
    <br>
    <br>
    <i>Existing Prescriptions</i>
  <% end %>
  <% @prescriptions.each do |prescription| %>
    <ul>
      <li>
        <small><i>Patient:</i></small> <%= link_to prescription.appointment.patient.full_name, patient_path(prescription.appointment.patient) %>
      </li>
      <li>
        <small><i>Drug:</i></small> <%= prescription.drug %>
      </li>
      <li>
        <small><i>Dosage:</i></small> <%= prescription.dosage_in_milligrams %> mg
      </li>
      <li>
        <small><i>Reason:</i></small> <%= prescription.appointment.ailment.description %>
      </li>
      <li>
        <small><i>Appointment Date:</i></small> <%= link_to prescription.appointment.scheduled_for.strftime("%b. %-d, %Y"), appointment_path(prescription.appointment) %>
      </li>
        <small><i><%= link_to "edit this prescription", edit_prescription_path(prescription) %></i></small>
      <%= form_tag prescription_path(prescription), method: 'delete' do %>
        <%= hidden_field_tag "id", prescription.id %>
        <%= submit_tag "Cancel Prescription" %>
      <% end %>
    </ul>
  <% end %>
  <br>
<% end %>
<br>
<%= link_to "All Medical Specialties", specialties_path %>
<br>
<%= link_to "All Registered Physicians", doctors_path %>